import type {
  Objekt,
  Speculant,
  TimelineEvent,
  NextStep,
} from './types'

// Dates are generated relative to "now" so the demo always looks current.
function at(daysOffset: number, hour = 9, minute = 0): string {
  const d = new Date()
  d.setDate(d.getDate() + daysOffset)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export const seedObjekt: Objekt[] = [
  {
    id: 'obj_gotgatan',
    adress: 'Götgatan 12',
    omrade: 'Södermalm, Stockholm',
    rum: 2,
    boarea: 58,
    pris: 4_950_000,
    status: 'budgivning',
    hue: 250,
    sald: false,
    slutpris: null,
    dagarPaMarknaden: null,
  },
  {
    id: 'obj_bergsund',
    adress: 'Bergsunds strand 31',
    omrade: 'Hornstull, Stockholm',
    rum: 3,
    boarea: 74,
    pris: 6_250_000,
    status: 'till_salu',
    hue: 205,
    sald: false,
    slutpris: null,
    dagarPaMarknaden: null,
  },
  {
    id: 'obj_sigtuna',
    adress: 'Sigtunagatan 6',
    omrade: 'Vasastan, Stockholm',
    rum: 1,
    boarea: 38,
    pris: 3_295_000,
    status: 'till_salu',
    hue: 150,
    sald: false,
    slutpris: null,
    dagarPaMarknaden: null,
  },
  {
    id: 'obj_kungsholm',
    adress: 'Kungsholms strand 145',
    omrade: 'Kungsholmen, Stockholm',
    rum: 4,
    boarea: 102,
    pris: 8_900_000,
    status: 'kommande',
    hue: 32,
    sald: false,
    slutpris: null,
    dagarPaMarknaden: null,
  },
]

export const seedSpeculanter: Speculant[] = [
  {
    id: 'spk_anna',
    objektId: 'obj_gotgatan',
    namn: 'Anna Lindqvist',
    telefon: '070-412 88 19',
    epost: 'anna.lindqvist@gmail.com',
    budgetMin: 4_800_000,
    budgetMax: 5_200_000,
    onskemal: ['Balkong', 'Nära tunnelbana', 'Högt i tak'],
    invandningar: ['Köket behöver renoveras'],
    intresseniva: 'hög',
    finansiering: 'lånelöfte',
    sammanfattning:
      'Mycket intresserad efter visningen. Bor i närområdet och vill snabbt vidare. Lånelöfte klart upp till 5,2 mkr.',
    createdAt: at(-2, 15, 10),
  },
  {
    id: 'spk_johan',
    objektId: 'obj_gotgatan',
    namn: 'Johan Berg',
    telefon: '073-905 21 47',
    epost: 'johan.berg@outlook.com',
    budgetMin: 4_500_000,
    budgetMax: 4_950_000,
    onskemal: ['Lugnt läge', 'Hiss'],
    invandningar: ['Gatuplan – orolig för insyn', 'Vill se föreningens ekonomi'],
    intresseniva: 'medel',
    finansiering: 'kontant',
    sammanfattning:
      'Kontantköpare, men tveksam till läget på gatuplan. Har lagt ett första bud under utgångspris.',
    createdAt: at(-2, 16, 30),
  },
  {
    id: 'spk_holm',
    objektId: 'obj_gotgatan',
    namn: 'Sara Holm',
    telefon: '076-338 04 92',
    epost: 'sara.holm@hotmail.com',
    budgetMin: null,
    budgetMax: 5_100_000,
    onskemal: ['Nära förskola', 'Balkong', 'Två sovrum'],
    invandningar: [],
    intresseniva: 'hög',
    finansiering: 'lånelöfte',
    sammanfattning:
      'Barnfamilj som söker i området. Kommer på nästa visning med partnern.',
    createdAt: at(-1, 11, 0),
  },
  {
    id: 'spk_erik',
    objektId: 'obj_bergsund',
    namn: 'Erik Sandberg',
    telefon: '070-771 56 03',
    epost: 'erik.sandberg@gmail.com',
    budgetMin: 5_900_000,
    budgetMax: 6_400_000,
    onskemal: ['Vattennära', 'Öppen planlösning'],
    invandningar: ['Vill ha besiktning innan bud'],
    intresseniva: 'medel',
    finansiering: 'lånelöfte',
    sammanfattning: 'Gillar läget vid vattnet. Avvaktar besiktningsprotokoll.',
    createdAt: at(-3, 13, 20),
  },
  {
    id: 'spk_petra',
    objektId: 'obj_bergsund',
    namn: 'Petra Nyström',
    telefon: '072-118 77 40',
    epost: 'petra.nystrom@gmail.com',
    budgetMin: null,
    budgetMax: null,
    onskemal: ['Balkong i söderläge'],
    invandningar: ['Tveksam till månadsavgiften'],
    intresseniva: 'låg',
    finansiering: 'oklart',
    sammanfattning: 'Tidig i processen, vill se fler objekt först.',
    createdAt: at(-4, 18, 5),
  },
  {
    id: 'spk_mikael',
    objektId: 'obj_sigtuna',
    namn: 'Mikael Ek',
    telefon: '070-655 12 88',
    epost: 'mikael.ek@gmail.com',
    budgetMin: 3_000_000,
    budgetMax: 3_400_000,
    onskemal: ['Förstagångsköp', 'Låg insats'],
    invandningar: [],
    intresseniva: 'hög',
    finansiering: 'lånelöfte',
    sammanfattning: 'Förstagångsköpare, redo att lägga bud vid rätt objekt.',
    createdAt: at(-1, 9, 45),
  },
]

export const seedTimeline: TimelineEvent[] = [
  {
    id: 'tl_g1',
    objektId: 'obj_gotgatan',
    speculantId: null,
    typ: 'visning',
    titel: 'Visning – 9 besökare',
    beskrivning: 'Bra tryck. Tre tydligt intresserade, två la egna anteckningar.',
    occurredAt: at(-2, 14, 0),
    synced: true,
  },
  {
    id: 'tl_g2',
    objektId: 'obj_gotgatan',
    speculantId: 'spk_anna',
    typ: 'samtal',
    titel: 'Samtal med Anna Lindqvist',
    beskrivning: 'Ringde efter visningen. Mycket intresserad, lånelöfte klart.',
    occurredAt: at(-2, 15, 12),
    synced: true,
  },
  {
    id: 'tl_g3',
    objektId: 'obj_gotgatan',
    speculantId: 'spk_johan',
    typ: 'mejl',
    titel: 'Mejl från Johan Berg',
    beskrivning: 'Frågor om föreningens ekonomi och planerade avgiftshöjningar.',
    occurredAt: at(-1, 9, 5),
    synced: true,
  },
  {
    id: 'tl_g4',
    objektId: 'obj_gotgatan',
    speculantId: 'spk_johan',
    typ: 'bud',
    titel: 'Bud 4 850 000 kr',
    beskrivning: 'Johan Berg la ett första bud, 100 000 kr under utgångspris.',
    occurredAt: at(-1, 17, 40),
    synced: true,
  },
  {
    id: 'tl_b1',
    objektId: 'obj_bergsund',
    speculantId: null,
    typ: 'visning',
    titel: 'Visning – 6 besökare',
    beskrivning: 'Lugnare visning. Erik Sandberg stannade länge.',
    occurredAt: at(-3, 12, 30),
    synced: true,
  },
  {
    id: 'tl_b2',
    objektId: 'obj_bergsund',
    speculantId: 'spk_erik',
    typ: 'anteckning',
    titel: 'Anteckning',
    beskrivning: 'Erik vill ha besiktningsprotokoll innan han lägger bud.',
    occurredAt: at(-3, 13, 25),
    synced: true,
  },
  {
    id: 'tl_s1',
    objektId: 'obj_sigtuna',
    speculantId: 'spk_mikael',
    typ: 'sms',
    titel: 'SMS från Mikael Ek',
    beskrivning: 'Vill boka privatvisning, kan på torsdag em.',
    occurredAt: at(-1, 8, 50),
    synced: true,
  },
]

export const seedNextSteps: NextStep[] = [
  {
    id: 'ns_anna',
    objektId: 'obj_gotgatan',
    speculantId: 'spk_anna',
    beskrivning: 'Ring Anna Lindqvist – hon är nära bud, följ upp Johans bud',
    deadline: at(0, 16, 0),
    prioritet: 'hög',
    klar: false,
  },
  {
    id: 'ns_johan',
    objektId: 'obj_gotgatan',
    speculantId: 'spk_johan',
    beskrivning: 'Skicka föreningens årsredovisning till Johan Berg',
    deadline: at(0, 12, 0),
    prioritet: 'medel',
    klar: false,
  },
  {
    id: 'ns_erik',
    objektId: 'obj_bergsund',
    speculantId: 'spk_erik',
    beskrivning: 'Mejla besiktningsprotokoll till Erik Sandberg',
    deadline: at(1, 10, 0),
    prioritet: 'hög',
    klar: false,
  },
  {
    id: 'ns_mikael',
    objektId: 'obj_sigtuna',
    speculantId: 'spk_mikael',
    beskrivning: 'Bekräfta privatvisning torsdag – Sigtunagatan 6',
    deadline: at(1, 14, 0),
    prioritet: 'medel',
    klar: false,
  },
]
